### ISSUE TITLE
wzrd.in is down?

### ISSUE THREAD

**Issue by pierreneter** [browserify/wzrd.in#183]
![wzrd in](https://user-images.githubusercontent.com/12815768/32432559-9f059f00-c30a-11e7-9ed2-25db1acc117a.PNG)

**Comment by mkrauser** [comment]
The SSL-Certificate expired yesterday. Please fix this asap!

**Comment by qgustavor** [comment]
Seems [it's the fourth time](https://github.com/browserify/wzrd.in/search?q=certificate&type=Issues) it stopped working. Someone know something to prevent it happening again?

**Comment by jfhbrook** [comment]
> The SSL-Certificate expired yesterday. Please fix this asap!

I'll look into it when I get home.

>  Someone know something to prevent it happening again?

As to why the letsencrypt cron job sometimes fails? That's a mystery. I think it's been different, stupid reasons each time.

> Seems it's the fourth time it stopped working. 

Keep in mind I maintain this on an entirely volunteer basis and nobody else has stepped up to the plate.

**Comment by qgustavor** [comment]
I mean, maybe someone had the same issues, knows how to avoid those and can
help you. Sadly I'm not good with this kind of issue as my experience with
Let's Encrypt it's a bit unusual (Apache on Windows, port 80 blocked,
testing server).

As Let's Encrypt warns when the certificate was't renewed maybe you're
renewing too close to the limit (to renew less times) and ignoring the
warnings. How about renewing a bit sooner? Doing so if it fails you get the
warning and then you can fix it without downtimes. Maybe that's not the
case, I'm just trying to help…

2017/11/06 14:50 "Joshua Holbrook" <notifications@github.com>:

The SSL-Certificate expired yesterday. Please fix this asap!

I'll look into it when I get home.

Someone know something to prevent it happening again?

As to why the letsencrypt cron job sometimes fails? That's a mystery. I
think it's been different, stupid reasons each time.

Seems it's the fourth time it stopped working.

Keep in mind I maintain this on an entirely volunteer basis and nobody else
has stepped up to the plate.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/browserify/wzrd.in/issues/183#issuecomment-342210714>,
or mute the thread

**Comment by jfhbrook** [comment]
Fixed.

I think the cron job was trying to write to a folder that it didn't have access to. I think I fixed it, but it's tough to test cron jobs so we'll see.

**Comment by Masterxilo** [comment]
It is down again.
