### ISSUE TITLE
multi-bundle fails to resolve peer dependencies

### ISSUE THREAD

**Issue by anvaka** [browserify/wzrd.in#73]
I noticed browserify cdn is failing to resolve peer dependencies, even when they are part of multi-bundle. 

E.g.:

```
curl 'http://wzrd.in/multi' --data-binary '{"dependencies":{"an":"latest","typeahead.an":"latest"}}'
```

This gives me:

```
Error: "browserify exited with code 1"

code: 1
stderr: Error: module "an" not found from "/tmp/typeahead.an114229-2259-1zh50r/node_modules/typeahead.an/index.js"

dirPath: /tmp/typeahead.an114229-2259-1zh50r
```

Here `typeahead.an` has `an` as a [peer dependency](https://github.com/anvaka/typeahead.an/blob/7d7177bdfb58e4e9fb36367fb4632d999e222a10/package.json#L30-L32).

**Comment by STRML** [comment]
Unfortunately, due to issues like https://github.com/facebook/react/issues/2402, it is often necessary for plugin authors to put `react` in a peerDep to avoid this hard-to-debug bug.

I understand what people are trying to do with making peerDependencies stricter but it appears we're caught between a rock and a hard place with this one. Damned if we put it in dependencies, and damned (in terms of compat with projects like this) if we don't.

If browserify-cdn installed peerDependencies it would be a big help. It is the npm 2.x behavior so it is technically "correct", even if the auto-installation (but not peerDependencies) will be deprecated in npm 3. For a service like this which should just be trying to compile the module as best it can, it makes sense to install these deps.

**Comment by voronianski** [comment]
@STRML @jfhbrook @maxogden @anvaka I see this is still an issue, related to https://github.com/jfhbrook/wzrd.in/issues/114

**Comment by jfhbrook** [comment]
It's also a wontfix

**Comment by voronianski** [comment]
@jfhbrook that's sad, any chance to get peer deps work?

**Comment by voronianski** [comment]
@jfhbrook is this happening because of npm v3 on wzrd.in server?

**Comment by voronianski** [comment]
I will just leave it here for some time https://github.com/jfhbrook/wzrd.in/blob/master/bundler/install.js#L12

**Comment by jfhbrook** [comment]
We're currently using npm@2.

**Comment by voronianski** [comment]
@jfhbrook hmm, so I don't understand why peer deps are not installed then..

**Comment by voronianski** [comment]
@jfhbrook I just investigated this issue a bit and found that `npm install` runs without errors but `npm install --production` results in this weird error `npm ERR! Cannot read property 'react' of undefined`.. probably will raise an issue in react-dom repo.

**Comment by voronianski** [comment]
@jfhbrook @maxogden maybe it's time to upgrade to npm@3?! it looks like there's no such error on that version and peer dependencies are not installed as well.

**Comment by Risto-Stevcev** [comment]
@maxogden So... is this an issue with browserify? because it's clear that `wzrd.in` multi bundles **do not** work the same way that `npm` does. This example wouldn't fail if the `dependencies` section were part of a `package.json` that gets `npm install`ed and then `browserify`d.

In all fairness to the lib devs that use `peerDependency` in this way, it's [not clear](https://docs.npmjs.com/files/package.json#peerdependencies) which side is right. From the [nodejs blog](https://nodejs.org/en/blog/npm/peer-dependencies/#the-solution-peer-dependencies):

> What we need is a way of expressing these "dependencies" between plugins and their host package. Some way of saying, "I only work when plugged in to version 1.2.x of my host package, so if you install me, be sure that it's alongside a compatible host." We call this relationship a peer dependency.

What's clear about the quote is that the plugin with the peerDependency will not work without the peerDependency being installed along side it. What's also clear is that npm1 and 2 will auto-install this dependency (and npm3 will give a warning). What **isn't** clear is whether or not a module import **could** fail if the peerDependency isn't installed. Some interpret that it could, other's don't, and it isn't clear who is right. But if it isn't explicitly mentioned in the docs, then it's not unreasonable to assume that the module import could fail without it's peerDepedency installed. And if I had to guess one practical reason (interpretations aside) why these libs (like motorcyclejs and cyclejs) use peerDependency in this way, is because npm1 and 2 will not try to flatten the dependency tree.

But ambiguity aside, I do think that `wzrd.in` should work like `npm` does to avoid any unnecessary headaches. Lib devs will write their code to work with npm, so if npm starts behaving like this then the lib devs will write it as a `dependency` rather than a `peerDependency`. But since it doesn't break on npm, so they keep writing it this way. It really should work like npm does.

**Comment by jfhbrook** [comment]
wzrd.in ultimately uses npm to install and bundle. Anything you're seeing here is a consequence of where the code is placed inside an install tree when browserifying.

If you can find a way to make peerDeps Just Work, then by all means. To me, it's such an antipattern that I don't even really care.

**Comment by Risto-Stevcev** [comment]
> EDIT: In the case of multibundles, we build each dependency separately

I think that might be the source of the problem. Why is it bundling each dependency separately? 

Regardless of whether or not you think it's an antipattern (I agree that it is), it should be consistent with how npm + browserify works locally if it's calling itself browserify as a service.

More specifically, what commands is wzrd.in running that makes the following fail but works when doing it locally?

```json
{
  "dependencies": {
    "@motorcycle/core": "^1.2.0",
    "@motorcycle/dom": "^1.3.0"
  }
}
```

```bash
$ npm install
$ ./node_modules/.bin/browserify -r @motorcycle/dom -t [ babelify --presets [ es2015 ] ] -s DOM -o dom.js
```
^ works locally ^

**Comment by jfhbrook** [comment]
I told you--- @motorcycle/core and @motorcycle/dom are built with entirely different builds, because multibundles code is just a convenience layer on top of singular bundles. Changing this would involve a large refactor and probably breakage.

If you want to take a crack at fixing it, go nuts.

**Comment by Risto-Stevcev** [comment]
Ugh.. oh well. That's a real bummer but I guess it is what it is... I'm not sure I would go through the trouble of supporting peerDependency if it's not a small fix either.

I posted an issue on their side so hopefully they'll get rid of the peerDependency and I don't have to resort to hacks.
